version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.webjars:jquery
    versions:
    - 3.5.1
  - dependency-name: org.webjars:angularjs
    versions:
    - 1.8.0
