spring.application.name=knowledgeroot
server.port=${KR_SERVER_PORT:8081}
spring.config.import=optional:file:.env[.properties],optional:file:./config/application-local.properties

# database configuration
spring.datasource.url=${KR_DB_URL:jdbc:mariadb://localhost:3306/knowledgeroot?createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Berlin}
spring.datasource.username=${KR_DB_USER:root}
spring.datasource.password=${KR_DB_PASSWORD:}

spring.jpa.open-in-view=false

# jdbc session handling
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=3600

# template
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/

# logging
logging.level.root=INFO
#logging.level.org.springframework.security=TRACE

# define storage driver - minio or file
knowledgeroot.storage.driver=${KR_STORAGE_DRIVER:minio}

# file storage
# local file system
file.storage-dir=${KR_FILE_STORAGE_DIR:./storage}

# minio storage
minio.url=${KR_MINIO_URL:http://localhost:9000}
minio.access-key=${KR_MINIO_ACCESS_KEY:}
minio.secret-key=${KR_MINIO_SECRET_KEY:}
minio.bucket=${KR_MINIO_BUCKET:knowledgeroot}
