<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Welcome to Knowledgeroot</h1>
        <p class="col-md-8 fs-4">Welcome to your new Knowledgebase...</p>
        <button class="btn btn-primary btn-lg" type="button" hx-get="/content/new" hx-target="#content">Create Content</button>
        <button class="btn btn-primary btn-lg" type="button" hx-get="/ui/page/new" hx-target="#content">Create a Page</button>
    </div>
</div>